"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from dotenv import load_dotenv
import os
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'shop',
    'accounts',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    
]

# ===========================
# JAZZMIN ADMIN CONFIG
# ===========================

# ============================
# JAZZMIN CONFIGURATION
# ============================

INSTALLED_APPS = [
    "jazzmin",                     # MUST BE FIRST
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # your apps
    "accounts",
    "shop",
]

JAZZMIN_SETTINGS = {
    # -------------------------
    # Branding
    # -------------------------
    "site_title": "Shopping Cart Admin",
    "site_header": "Shopping Cart",
    "site_brand": "Shopping Cart",
    "site_logo": None,
    "login_logo": None,
    "site_icon": None,

    # -------------------------
    # Layout
    # -------------------------
    "navigation_expanded": True,
    "show_sidebar": True,
    "order_with_respect_to": ["shop", "accounts"],
    "hide_apps": [],

    # -------------------------
    # HIDE INTERNAL / NOISY MODELS
    # -------------------------
    "hide_models": [
        # Shop internals
        "shop.CartItem",
        "shop.OrderItem",
        "shop.WishlistItem",
        "shop.ProductImage",
        "shop.InventoryRecord",
        "shop.SupplierProduct",

        # Account internals
        "accounts.UserSession",
        "accounts.UserActivityLog",
        "accounts.PasswordResetRequest",
        "accounts.TwoFactorAuth",
    ],

    # -------------------------
    # ICONS (minimal, readable)
    # -------------------------
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "shop.Product": "fas fa-box",
        "shop.Category": "fas fa-tags",
        "shop.Order": "fas fa-receipt",
        "shop.Payment": "fas fa-money-bill",
        "shop.Discount": "fas fa-percent",
        "shop.GiftCard": "fas fa-gift",
        "shop.Supplier": "fas fa-truck",

        "accounts.User": "fas fa-user",
        "accounts.UserRole": "fas fa-id-badge",
    },

    # -------------------------
    # DASHBOARD GROUPING (NO DUMP)
    # -------------------------
    "dashboard_links": [
        {
            "name": "🛒 Store",
            "icon": "fas fa-store",
            "models": [
                "shop.Product",
                "shop.Category",
                "shop.Supplier",
            ],
        },
        {
            "name": "📦 Orders",
            "icon": "fas fa-box",
            "models": [
                "shop.Order",
                "shop.Payment",
                "shop.Shipment",
                "shop.ReturnRequest",
            ],
        },
        {
            "name": "📣 Marketing",
            "icon": "fas fa-bullhorn",
            "models": [
                "shop.Discount",
                "shop.GiftCard",
                "shop.Review",
            ],
        },
        {
            "name": "👤 Users",
            "icon": "fas fa-users",
            "models": [
                "accounts.User",
                "accounts.UserRole",
            ],
        },
    ],

    # -------------------------
    # TOP MENU (CLEAN)
    # -------------------------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],

    # -------------------------
    # UI BEHAVIOR
    # -------------------------
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
    },
}

# ============================
# UI TWEAKS (EYE FRIENDLY)
# ============================

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",                 # clean, light
    "dark_mode_theme": None,           # disable dark (Jazzmin dark is noisy)

    "navbar": "navbar-light",
    "sidebar": "sidebar-light-primary",
    "accent": "accent-primary",
    "brand_colour": "navbar-light",

    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,

    "body_small_text": True,
    "footer_small_text": True,

    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
}


ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
